ALTER TYPE "AuditAction" ADD VALUE 'MOCK_INTERVIEW_ADMIN_HARD_DELETE';
ALTER TYPE "AuditAction" ADD VALUE 'MOCK_CV_ADMIN_VIEW_DETAIL';
ALTER TYPE "AuditAction" ADD VALUE 'MOCK_CV_ADMIN_RETRY_ANALYSIS';
ALTER TYPE "AuditAction" ADD VALUE 'MOCK_CV_ADMIN_RETRY_QUESTIONS';
ALTER TYPE "AuditAction" ADD VALUE 'MOCK_CV_ADMIN_HARD_DELETE';
ALTER TYPE "AuditAction" ADD VALUE 'MOCK_CV_INTERVIEW_ADMIN_RETRY_SCORING';
ALTER TYPE "AuditAction" ADD VALUE 'MOCK_CV_INTERVIEW_ADMIN_HARD_DELETE';
